//package main.ui;
//
//import main.model.pos.CarriedItems;
//import main.model.pos.Item;
//
//import javax.swing.*;
//import java.awt.*;
//import java.awt.event.ActionEvent;
//import java.awt.event.ActionListener;
//
//public class addItem {
//    private JPanel panel1;
//    private JTextField textField1;
//    private JButton button1;
//    private JButton button2;
//    private JLabel label1;
//    private JLabel label2;
//    private JTextField textField2;
//    static JFrame frame;
//    private static CarriedItems carries;
//    Item z;
//
//    public addItem() {
//        textField1.addActionListener(new ActionListener() {
//            @Override
//            public void actionPerformed(ActionEvent e) {
//                String a = textField1.getText();
//                    z = carries.addItem(a);
//                    if (z.getDescription() == null) {
//                        ManualDescrip.manDes(z, carries);
//                        frame.dispose();
//                    }
//                    textField1.setText("");
//                    textField1.setVisible(false);
//                    label1.setText("Is the following description correct?");
//                    label2.setVisible(true);
//                    label2.setText(z.getDescription());
//                    button1.setVisible(true);
//                    button2.setVisible(true);
//            }
//        });
//        button2.addActionListener(new ActionListener() {
//            @Override
//            public void actionPerformed(ActionEvent e) {
//                ProductInfo.productInfo(z, carries);
//                frame.dispose();
//            }
//        });
//        button1.addActionListener(new ActionListener() {
//            @Override
//            public void actionPerformed(ActionEvent e) {
//                ManualDescrip.manDes(z, carries);
//                frame.dispose();
//            }
//        });
//    }
//
//    public static void addStuff(CarriedItems items) {
//        carries = items;
//        System.out.println(carries);
//        frame = new JFrame("Add Item");
//        frame.setContentPane(new addItem().panel1);
//        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
//        frame.pack();
//        frame.setVisible(true);
//    }
//
//    {
//// GUI initializer generated by IntelliJ IDEA GUI Designer
//// >>> IMPORTANT!! <<<
//// DO NOT EDIT OR ADD ANY CODE HERE!
//        $$$setupUI$$$();
//    }
//
//    /**
//     * Method generated by IntelliJ IDEA GUI Designer
//     * >>> IMPORTANT!! <<<
//     * DO NOT edit this method OR call it in your code!
//     *
//     * @noinspection ALL
//     */
//    private void $$$setupUI$$$() {
//        panel1 = new JPanel();
//        panel1.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(5, 2, new Insets(0, 0, 0, 0), -1, -1));
//        label1 = new JLabel();
//        label1.setText("Enter Product Code");
//        panel1.add(label1, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 2, com.intellij.uiDesigner.core
// .GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.G
// ridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0,
// false));
//        label2 = new JLabel();
//        Font label2Font = this.$$$getFont$$$(null, Font.BOLD, -1, label2.getFont());
//        if (label2Font != null) label2.setFont(label2Font);
//        label2.setText("Label");
//        label2.setVisible(false);
//        panel1.add(label2, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 2, com.intellij.uiDesigner.core.
// GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.Gr
// idConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0,
// false));
//        button1 = new JButton();
//        button1.setText("No");
//        button1.setVisible(false);
//        panel1.add(button1, new com.intellij.uiDesigner.core.GridConstraints(4, 0, 1, 1, com.intellij.uiDesigner.cor
// e.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesign
// er.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, co
// m.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
//        button2 = new JButton();
//        button2.setText("Yes");
//        button2.setVisible(false);
//        panel1.add(button2, new com.intellij.uiDesigner.core.GridConstraints(4, 1, 1, 1, com.intellij.uiDesigner.core.
// GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner
// .core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.
// intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
//        textField2 = new JTextField();
//        textField2.setVisible(false);
//        panel1.add(textField2, new com.intellij.uiDesigner.core.GridConstraints(3, 0, 1, 2, com.intellij.uiDesigner.c
// ore.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesign
// er.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, n
// ew Dimension(150, -1), null, 0, false));
//        textField1 = new JTextField();
//        panel1.add(textField1, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 2, com.intellij.uiDesigner.c
// ore.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesign
// er.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, n
// ew Dimension(150, -1), null, 0, false));
//    }
//
//    /**
//     * @noinspection ALL
//     */
//    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
//        if (currentFont == null) return null;
//        String resultName;
//        if (fontName == null) {
//            resultName = currentFont.getName();
//        } else {
//            Font testFont = new Font(fontName, Font.PLAIN, 10);
//            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
//                resultName = fontName;
//            } else {
//                resultName = currentFont.getName();
//            }
//        }
//        return new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.get
// Size());
//    }
//
//    /**
//     * @noinspection ALL
//     */
//    public JComponent $$$getRootComponent$$$() {
//        return panel1;
//    }
//}
