//package main.ui;
//
//import main.model.pos.Item;
//import main.model.pos.Transaction;
//
//import javax.swing.*;
//import java.awt.*;
//import java.awt.event.ActionEvent;
//import java.awt.event.ActionListener;
//import java.util.List;
//
//public class SellByWeight {
//    private JTextField textField1;
//    private JPanel panel1;
//    static Transaction transaction;
//    static Item item;
//    static List<Double> price;
//    static JLabel total;
//    static DefaultListModel<String> y = new DefaultListModel<>();
//    static JFrame frame;
//
//    public SellByWeight() {
//        textField1.addActionListener(new ActionListener() {
//            @Override
//            public void actionPerformed(ActionEvent e) {
//                double a = Double.parseDouble(textField1.getText());
//                transaction.amount.add(a);
//                int cost = (int) (a * item.getPrice());
//                //price.add((double) cost);
//                transaction.addTotal(cost);
//                total.setText(display.toMoney(transaction.getTotal()));
//                transaction.amount.add(a);
//                y.addElement(item.getDescription());
//                frame.dispose();
//            }
//        });
//    }
//
//    public static void SBW(Transaction transac, Item item1, JList<String> items, JLabel total1, DefaultListModel<Stri
// ng> x) {
//        y = x;
//        item = item1;
//        transaction = transac;
//        total = total1;
//       // price = price1;
//        frame = new JFrame("Weight");
//        frame.setContentPane(new SellByWeight().panel1);
//        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
//        frame.pack();
//        frame.setVisible(true);
//
//    }
//
//    {
//// GUI initializer generated by IntelliJ IDEA GUI Designer
//// >>> IMPORTANT!! <<<
//// DO NOT EDIT OR ADD ANY CODE HERE!
//        $$$setupUI$$$();
//    }
//
//    /**
//     * Method generated by IntelliJ IDEA GUI Designer
//     * >>> IMPORTANT!! <<<
//     * DO NOT edit this method OR call it in your code!
//     *
//     * @noinspection ALL
//     */
//    private void $$$setupUI$$$() {
//        panel1 = new JPanel();
//        panel1.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
//        textField1 = new JTextField();
//        panel1.add(textField1, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.
// core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesig
// ner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null,
// new Dimension(150, -1), null, 0, false));
//        final JLabel label1 = new JLabel();
//        label1.setText("Enter Weight");
//        panel1.add(label1, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core
// .GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.G
// ridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0,
// false));
//    }
//
//    /**
//     * @noinspection ALL
//     */
//    public JComponent $$$getRootComponent$$$() {
//        return panel1;
//    }
//}
